# Generated by Django 5.1.3 on 2024-11-21 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("start_date", models.DateField(help_text="Class start date")),
                ("start_time", models.TimeField(help_text="Class start time")),
                ("end_time", models.TimeField(help_text="Class end time")),
                (
                    "lunch_break_start",
                    models.TimeField(help_text="Lunch break start time"),
                ),
                ("lunch_break_end", models.TimeField(help_text="Lunch break end time")),
                (
                    "period_duration",
                    models.IntegerField(
                        default=45, help_text="Duration of each class period in minutes"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Holiday name", max_length=100)),
                (
                    "date",
                    models.DateField(help_text="Date of the holiday", unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Subject name", max_length=100)),
                (
                    "teacher_name",
                    models.CharField(
                        help_text="Teacher assigned to the subject", max_length=100
                    ),
                ),
                (
                    "total_hours",
                    models.PositiveIntegerField(
                        help_text="Total hours for the subject per year"
                    ),
                ),
                (
                    "class_assigned",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="timetable.class",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Timetable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Date of the timetable entry")),
                ("start_time", models.TimeField(help_text="Start time of the period")),
                ("end_time", models.TimeField(help_text="End time of the period")),
                (
                    "teacher_name",
                    models.CharField(
                        help_text="Teacher assigned for this period", max_length=100
                    ),
                ),
                (
                    "class_assigned",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetables",
                        to="timetable.class",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetables",
                        to="timetable.subject",
                    ),
                ),
            ],
        ),
    ]
