# Generated by Django 5.1.3 on 2024-11-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="class",
            name="lunch_break_end",
        ),
        migrations.RemoveField(
            model_name="class",
            name="lunch_break_start",
        ),
        migrations.RemoveField(
            model_name="class",
            name="period_duration",
        ),
        migrations.AddField(
            model_name="class",
            name="lunch_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="class",
            name="lunch_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="class",
            name="end_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="class",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="class",
            name="start_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="class",
            name="start_time",
            field=models.TimeField(),
        ),
    ]
