# Generated by Django 5.1.3 on 2024-11-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0002_remove_class_lunch_break_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="period_duration",
            field=models.IntegerField(
                default=45, help_text="Duration of each period in minutes"
            ),
        ),
    ]
