# Generated by Django 5.1.3 on 2024-11-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0003_class_period_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetable",
            name="total_hours",
            field=models.IntegerField(default=1, help_text="Hours for this period"),
        ),
    ]
