# Generated by Django 5.1.3 on 2024-11-21 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0004_timetable_total_hours"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timetable",
            name="total_hours",
        ),
        migrations.AlterField(
            model_name="timetable",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetables",
                to="timetable.subject",
            ),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="teacher_name",
            field=models.CharField(
                blank=True,
                help_text="Teacher assigned for this period",
                max_length=100,
                null=True,
            ),
        ),
    ]
