# Generated by Django 5.1.3 on 2024-11-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "timetable",
            "0005_remove_timetable_total_hours_alter_timetable_subject_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="holiday",
            name="is_custom",
            field=models.BooleanField(
                default=False, help_text="Is this a manually added holiday?"
            ),
        ),
    ]
